on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Run a one-line script
      run: echo "Hello, GitHub Actions! 專案成功觸發！"

    - name: Check Ubuntu Version
      run: lsb_release -a
